# Site settings
title: Patdec Tech
email: blog@patriceandre.com
description: > # this means to ignore newlines until "baseurl:"
  Opensuse & Ruby on Rails.<br />
  Blog de Patrice André - Développeur Ruby on Rails
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://patec.github.io" # the base hostname & protocol for your site
twitter_username: PatriceAndr1
github_username:  patdec

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

